[package]
name = "linux-firmware"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
package-name = "linux-firmware"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
url = "https://www.kernel.org/pub/linux/kernel/firmware/linux-firmware-20230625.tar.xz"
sha512 = "0e48aa7f63495485426d37491c7cb61843165625bd47f912c5d83628c6de871759f1a78be3af3d651f7c396bd87dff07e21ba7afc47896c1c143106d5f16d351"

[[package.metadata.build-package.external-files]]
url = "https://www.kernel.org/pub/linux/kernel/firmware/linux-firmware-20230625.tar.sign"
sha512 = "dda47cc25d2d4eb15018493a162209f168a9dbf38536a8c554be0fad29bbad7854027e6bda1aa8bd6928bfa2805c8490d12a5ef4cf295cd708c9dccdaeb2dcc5"
