name: Validate CHANGELOG
on:
  pull_request:
    branches: [develop]
    paths:
      - 'CHANGELOG.md'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./tools/validate-changelog.sh
